#!/usr/bin/env bash
# Configures a new ubuntu machine
#+ Install nginx
#+ Nginx should listen to port 80

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
