#!/usr/bin/env bash
# A script that uses a if, else if and else statement to display best school 10 times
x=1
while [ $x -le 10 ]
do
	if [ $x -eq 4 ]
	then
		echo "bad luck"
	elif [ $x -eq 8 ]
	then
		echo "good luck"
       	else
		echo "Best School"
	fi
	((x++))
done
