#!/usr/bin/env bash
# A script that displays the current time
hour=0
while [ $hour -le 12 ]
do
    	echo "Hour: $hour"
    	minutes=1
    	while [ $minutes -lt 60 ]
    	do
		echo "$minutes"
		((minutes++))
    	done
    	((hour++))
done
