#!/usr/bin/env bash
# Do previous task with 7 or less lines
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.con
sudo -u nginx service nginx start
